#!/bin/bash
echo "Styles GéoPicardie (branche $BRANCH)"

PROJECT_PATH="/srv/style-osm-geopicardie/"

cd $PROJECT_PATH
git checkout $BRANCH

for STYLE_PATH in $(find $PROJECT_PATH/styles -mindepth 1 -maxdepth 1 -type d); do
	STYLE=`basename $STYLE_PATH`
	cd $STYLE_PATH
	echo "Traitement style $STYLE"
	echo -n "    Création MML local"
	cat project.mml|prod_project_mml  > project.loc.mml

	if [ ! -f project.loc.mml ]; then
		echo "      project.loc.mml existe pas"
		exit 1
	fi
	echo "."
	echo -n "    Création mapnik.xml"
	carto project.loc.mml > mapnik.xml

	if [ $? -gt 0 ]; then
		echo "      échec création mapnik.xml (carto)"
		exit 1
	fi

	if [ ! -d /srv/mapproxy ]; then
		mkdir -p /srv/mapproxy
	fi
	if [ ! -f /srv/mapproxy/mapproxy.layers.yaml ]; then
		echo "layers:" > /srv/mapproxy/mapproxy.layers.yaml
	fi
	if [ ! -f /srv/mapproxy/mapproxy.sources.yaml ]; then
		echo "sources:" > /srv/mapproxy/mapproxy.sources.yaml
	fi
	cat >> /srv/mapproxy/mapproxy.layers.yaml << EOF
  - name: $STYLE
    title: $STYLE
    sources: [mapnik_$STYLE]
EOF
	cat >> /srv/mapproxy/mapproxy.sources.yaml << EOF
  mapnik_$STYLE:
    type: mapnik
    mapfile: $STYLE_PATH/mapnik.xml
EOF
	echo "."
done;

echo "Configuration mapproxy"
cat > /srv/mapproxy/mapproxy.yaml << EOF
services:
  demo:
  wms:
    srs: ['EPSG:4326', 'EPSG:3857', 'EPSG:2154']
    md:
      title: Géopicardie OSM WMS Service
      abstract: Service WMS

caches:

grids:
    webmercator:
        base: GLOBAL_WEBMERCATOR
    mercatornw:
        base: GLOBAL_WEBMERCATOR
        origin: nw

globals:
EOF

cat /srv/mapproxy/mapproxy.layers.yaml /srv/mapproxy/mapproxy.sources.yaml >> /srv/mapproxy/mapproxy.yaml

# il faut un dossier img commun aux styles

mkdir /srv/mapproxy/www
ln -s $STYLE_PATH/img /srv/mapproxy/www/img

mapproxy-util create -t wsgi-app -f /srv/mapproxy/mapproxy.yaml /srv/mapproxy/www/config.py

chmod a+x /srv/mapproxy/www/config.py

echo "Configuration apache"
cat >  /etc/apache2/conf-enabled/mapproxy.conf << EOF
WSGIScriptAlias /mapproxy /srv/mapproxy/www/config.py
WSGIDaemonProcess mapproxy user=mapproxy group=mapproxy processes=2 threads=4
WSGIProcessGroup mapproxy

<Directory /srv/mapproxy/www>
  Require all granted
</Directory>
EOF

echo "Démarre apache" 1>&2

/usr/sbin/apache2ctl -D FOREGROUND
